### ISSUE TITLE
memory access violation during rocsparse-test on Amethyst XT

### ISSUE THREAD

**Issue by HQS-Peter** [ROCmSoftwarePlatform/rocSPARSE#217] opened 2020-12-22 12:22 UTC
I tried to follow the installation instruction for a AMD Tonga card on my Laptop.
I successfully obtained:
```
$ rocminfo   | grep Name
  Name:                    Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz
  Marketing Name:          Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz
  Vendor Name:             CPU                                
  Name:                    gfx802                             
  Marketing Name:          Amethyst XT [Radeon R9 M295X / M390X]
  Vendor Name:             AMD                                
  Name:                    amdgcn-amd-amdhsa--gfx802          
``` 
The band width test also gives reasonable results
```
$ rocm-bandwidth-test | grep "Device:"
  Device: 0,  Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz
  Device: 1,  Amethyst XT [Radeon R9 M295X / M390X],  01:0.0

$ rocm-bandwidth-test | tail

          Bdirectional copy peak bandwidth GB/s

          D/D       0           1           

          0         N/A         16.868657   

          1         16.868657   N/A         
```
After installing rocSPARSE and starting `./clients/staging/rocsparse-test ` the tests run rather long finally stopping with a  memory access violation:
``` 
Query device success: there are 1 devices
Device ID 0: Amethyst XT [Radeon R9 M295X / M390X]
-------------------------------------------------------------------------
with 4096MB memory, clock rate 723MHz @ computing capability 8.0
maxGridDimX 2147483647, sharedMemPerBlock 64KB, maxThreadsPerBlock 1024
wavefrontSize 64
-------------------------------------------------------------------------
Using device ID 0 (Amethyst XT [Radeon R9 M295X / M390X]) for rocSPARSE
-------------------------------------------------------------------------
rocSPARSE version: 1.19.3-916-e69bb42
[==========] Running 119628 tests from 201 test cases.
[----------] Global test environment set-up.
[----------] 192 tests from quick/axpby
[ RUN      ] quick/axpby.level1/i32_f32_r_1200_5_1_0_1_0_0b
[       OK ] quick/axpby.level1/i32_f32_r_1200_5_1_0_1_0_0b (22 ms)
[ RUN      ] quick/axpby.level1/i32_f32_r_1200_10_1_0_1_0_0b
[       OK ] quick/axpby.level1/i32_f32_r_1200_10_1_0_1_0_0b (1 ms)
......
......
[ RUN      ] pre_checkin/spmv_ell.level2/i32_f32_r_0_4441_2_0_0_0_NT_1b_rand
[       OK ] pre_checkin/spmv_ell.level2/i32_f32_r_0_4441_2_0_0_0_NT_1b_rand (1 ms)
[ RUN      ] pre_checkin/spmv_ell.level2/i32_f32_r_0_10000_2_0_0_0_NT_1b_rand
[       OK ] pre_checkin/spmv_ell.level2/i32_f32_r_0_10000_2_0_0_0_NT_1b_rand (2 ms)
[ RUN      ] pre_checkin/spmv_ell.level2/i32_f32_r_7111_0_2_0_0_0_NT_1b_rand
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

I installed the sources from the develop branch of yesterday and changed the CMakeLists.txt as suggested in posts.
If there's anything I can do helping to fix this issue,please let me know.

**Comment by ntrost57** [comment] 2020-12-23 08:05
Unfortunately, we do not support gfx802 in rocsparse.
What you could try:
- add `-DAMDGPU_TARGETS=gfx802` to cmake buildchain (do not use install.sh script)
- build from master branch (unless you do that already)

**Comment by HQS-Peter** [comment] 2020-12-23 08:25
I had added `gfx802`to the 
```
set(AMDGPU_TARGETS gfx802;gfx803;gfx900;gfx906;gfx908 .....
```
list in CMakeLists.txt, otherwise it doesn't work. 
It's unfortunate that you don't support the gfx802, it seems that most of/ lots of roc_sparse is running fine.
I see a few accuracy problems in the first few tests, but grepping for "OK" in the output of rocsparse-test gives me
```
$ grep "OK ]" test.out | wc
 116868  701208 9762028
```
which are quite a bunch of OKs. 
I'll try the master instead of the develop branch,

**Comment by ntrost57** [comment] 2020-12-23 08:32
Slightly different rounding can happen on some unsupported devices, this should not be critical.

**Comment by HQS-Peter** [comment] 2020-12-23 12:09
Seems like the master branch doesn't help. the test actually ends without a message with
```
[ RUN      ] pre_checkin/spmv_ell.level2/i32_f32_r_0_4441_2_0_0_0_NT_1b_rand
[       OK ] pre_checkin/spmv_ell.level2/i32_f32_r_0_4441_2_0_0_0_NT_1b_rand (1 ms)
[ RUN      ] pre_checkin/spmv_ell.level2/i32_f32_r_0_10000_2_0_0_0_NT_1b_rand
[       OK ] pre_checkin/spmv_ell.level2/i32_f32_r_0_10000_2_0_0_0_NT_1b_rand (1 ms)
[ RUN      ] pre_checkin/spmv_ell.level2/i32_f32_r_7111_0_2_0_0_0_NT_1b_rand
```
which looks like the same position as before. I didn't get a message in the terminal, but according to `dmesg` 
```
[Mi Dez 23 12:47:25 2020] rocsparse-test[42135]: segfault at 7f0c00000000 ip 00007f0cd17db9a9 sp 00007ffcf4eee010 error 4 in librocsparse.so.0.1[7f0cd17d8000+45b000]
[Mi Dez 23 12:47:25 2020] Code: ad c7 ff ff 8b 18 e8 a6 ca ff ff eb 8d e8 1f cb ff ff 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 53 48 85 ff 74 25 48 89 fb <80> 3f 00 74 26 48 8b 7b 58 48 85 ff 74 05 e8 e4 c8 ff ff 48 8b 7b
```
it was a segfault.
I also have less "OK" compared to the develop branch:
```
 grep "OK ]" test-master.out | wc
 114292  685752 9591528
```
Best regards,
Peter

**Comment by ntrost57** [comment] 2020-12-23 12:50
It's less tests because develop branch contain additional features and thus more unit tests.

**Comment by HQS-Peter** [comment] 2020-12-23 13:12
Thanks for the explanation.
Anyways, in both cases `pre_checkin/spmv_ell.level2/i32_f32_r_7111_0_2_0_0_0_NT_1b_rand` leads to a segfault.
I'm afraid there's there's not much I can do. If there's interest I can re-run the tests.

**Comment by ntrost57** [comment] 2020-12-23 13:14
Could also be caused by insufficient memory (4GB).

**Comment by HQS-Peter** [comment] 2020-12-23 13:27
Could one switch of those tests?

**Comment by ntrost57** [comment] 2020-12-23 13:29
No, unfortunately not.

**Comment by ntrost57** [comment] 2021-01-22 08:16
Closing this as gfx802 is not supported.

**Closed by ntrost57** 2021-01-22 08:16 UTC
