### ISSUE TITLE
[Issue]: `example_bsrsm` and `example_fortran_spmv` have device memory access faults

### ISSUE THREAD

**Issue by Beanavil** [ROCmSoftwarePlatform/rocSPARSE#430] opened 2024-12-18 12:41 UTC
### Problem Description

We got some examples failures when running all the examples from rocSPARSE:
- `example_bsrsm` failing after rocm-6.2.4. Tracked the culprit commit to [2934d0609d18a8540710c33e30e87ae20bde6344](https://github.com/ROCm/rocSPARSE/commit/2934d0609d18a8540710c33e30e87ae20bde6344).
- `example_fortran_spmv` failing since unknown (tested up to 6.1.0)

We are using the `rocm/rocm-terminal` docker image when running these. These fail in several devices, not only MI100. The architectures for which they fail are:
- gfx906 (Vega20)
- gfx90a (MI200)
- gfx908 (MI100)
- gfx1030 (V620)
- gfx1100 (TR 3970X)

### Operating System

Ubuntu 20.04

### CPU

AMD EPYC 7713P 64-Core Processor

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 6.3.0

### ROCm Component

rocSPARSE

### Steps to Reproduce

```shell
CC=/opt/rocm/bin/hipcc CXX=/opt/rocm/bin/hipcc FC=gfortran cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D BUILD_CLIENTS_SAMPLES=ON -D AMDGPU_TARGETS="<targets>"
```
```shell
cmake --build build --target example_fortran_spmv # or example_bsrsm
```
```shell
./build/clients/staging/example_fortran_spmv # or example_bsrsm
```

**Comment by ppanchad-amd** [comment] 2024-12-18 15:24
Hi @Beanavil. Internal ticket has been created to investigate your issue. Thanks!

**Comment by jsandham** [comment] 2024-12-19 00:12
@Beanavil Thanks for identifying these issues in the samples. I have tracked down the cause and have a PR up now that fixes them. Ill close this issue once the PR is merged to develop.

**Comment by jsandham** [comment] 2024-12-23 18:50
Fix merged to develop

**Closed as completed** 2024-12-23 18:49 UTC
Labels: Under Investigation
